# Generated by Django 2.0.2 on 2019-12-09 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20191209_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appusers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
